# Dockerfile.mysql
FROM mysql:8.2

# Environment variables for database initialization
ENV MYSQL_DATABASE=app_db
ENV MYSQL_USER=app_user
ENV MYSQL_PASSWORD=1234
ENV MYSQL_ROOT_PASSWORD=root_password

# Expose default MySQL port
EXPOSE 3306
